First commit
damirj/AttendanceApp pull request #1
Opened 2019-10-02 07:43 UTC by damirj

2019-10-02 08:29 UTC, LukaKordic commented on app/src/main/java/hr/damirjurkovic/attendance/adapters/CourseHolder.kt
> +        }
You can replace this if else block with 'when'

2019-10-02 08:32 UTC, Gocy commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="hr.damirjurkovic.attendance.activity.ContainerActivity">
If you wan't for app that works only in portrait mode add screenOrientation="portrait" to every activity

2019-10-02 08:38 UTC, goranluketic requested changes

2019-10-02 08:38 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/common/AndroidExtensions.kt
> +    message: String = "Are you sure?",
remove hardcoded strings from extensions

2019-10-02 08:38 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/db/DaoProvider.kt
> +                    context.getString(R.string.DbName)
it is not wrong if database name is inside Constants.kt

2019-10-02 08:38 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/fragments/DeleteAlertDialog.kt
> +        builder.setMessage(getString(R.string.areYouSure))
Use extension

2019-10-02 08:41 UTC, LukaKordic commented on app/src/main/java/hr/damirjurkovic/attendance/adapters/ViewPagerAdapter.kt
> +
Here you can create list of fragments like this: 
`val fragmentList = listOf(AttendanceFragment.newInstance(), StatisticsFragment.newInstance())`

2019-10-02 08:42 UTC, LukaKordic commented on app/src/main/java/hr/damirjurkovic/attendance/adapters/ViewPagerAdapter.kt
> +        }
You can then replace all of this with just 
`return fragmentList[position]`

2019-10-02 08:46 UTC, LukaKordic commented on app/src/main/java/hr/damirjurkovic/attendance/db/DaoProvider.kt
> +                    context.getString(R.string.DbName)
You can keep database name in Constants file. It will never get translated so you don't have to put it into strings.xml

2019-10-02 08:49 UTC, LukaKordic commented on app/src/main/java/hr/damirjurkovic/attendance/fragments/ChangeAttendanceDialogFragment.kt
> +        )
Is there a reason you are setting these parameters in code rather than xml?

2019-10-02 08:54 UTC, LukaKordic requested changes
Please make all suggested changes before merge

2019-10-02 09:12 UTC, damirj commented on app/src/main/java/hr/damirjurkovic/attendance/fragments/DeleteAlertDialog.kt
> +        builder.setMessage(getString(R.string.areYouSure))
That class is no longer in use I forgot to delete it. But i will try to remember to fetch strings from resources.

2019-10-02 09:16 UTC, damirj commented on app/src/main/java/hr/damirjurkovic/attendance/adapters/ViewPagerAdapter.kt
> +        }
mind = blown

2019-10-02 09:23 UTC, damirj commented on app/src/main/java/hr/damirjurkovic/attendance/fragments/ChangeAttendanceDialogFragment.kt
> +        )
I did put it in xml, but it didn't work so i've put it also in code and it worked, so I left it there.

2019-10-02 09:23 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/fragments/DeleteAlertDialog.kt
> +        builder.setMessage(getString(R.string.areYouSure))
ok

2019-10-02 09:50 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/ui/course/details/view/fragments/CourseDetailsFragment.kt
> +        when (attendance) {
you can use here if(attendance){logic for true} else {logic for false}

2019-10-07 13:57 UTC, LukaKordic reviewed
You're making good progress with this. Try doing code formatting more often while writing code (option + command + L)

2019-10-09 13:53 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/persistence/CourseRepository.kt
> +    }
you can inline these methods and remove return type

2019-10-09 13:55 UTC, Gocy commented on app/src/main/java/hr/damirjurkovic/attendance/ui/course/details/presentation/CourseDetailsViewModel.kt
> +    }
do you really need this function? You can pass id to the getCourse and then you don't need setCourseID and store Id inside ViewModel

2019-10-09 13:57 UTC, goranluketic reviewed
just some small stuff commented

2019-10-11 07:58 UTC, merged